### ISSUE TITLE
missing meshclust

### ISSUE THREAD

**Issue by maziz2** [BioinformaticsToolsmith/Identity#3]
Hi 

I downloaded the latest release. I compiled it successfully however i see the identity binary only. There is no MeShClust binary. I dont see any meshclust folder in the src

thanks

**Comment by hani-girgis** [comment]
Hi. 

I have tried installing MeShclust using the posted instructions and I can see the meshclust binary. Also, I can see the meshclust folder under source. How did you download the code? How did you install it?

Best regards, 

Hani Z. Girgis, PhD

**Comment by maziz2** [comment]
i downloaded the Jan 13, 2022 release. the meshclust folder is missing in the compressed source. I can see that folder on your git so i just dowloaded your entire git and compiled and it worked. 

Thanks
