### ISSUE TITLE
Is it possible to cluster the reads?

### ISSUE THREAD

**Issue by vahidAK** [BioinformaticsToolsmith/Identity#4]
Hi @benjamin-james ,

I was wondering if it is possible to cluster reads/contigs based on the similarity in sequence?
For example, let's say I have 1000 contigs and want to find out how they cluster together based on the sequence similarity?

Thanks,
Vahid

**Comment by hani-girgis** [comment]
Hi, Vahid!

Sorry for my late response.

Yes, you can cluster 1000 contigs based on sequence similarity. 

Let me know if you have further questions.

Best, 

Hani Z. Girgis, PhD
