### ISSUE TITLE
Interpretation of output

### ISSUE THREAD

**Issue by LiverpoolHarry** [BioinformaticsToolsmith/Identity#5]
MeshClust looks like just what I want for clustering sets of haplotye alleles. Thanks for writing it.
Please can you add to the documentation a description of the columns in the output file? I assume that column 1 is the cluster number and column 2 is obviously the sequence id. Column 3 looks like some measure of similarity but to what? What is column 4?
Thanks Harry

**Comment by hani-girgis** [comment]
Hello, Harry!

I have added the interpretation of MeShClust's output to the instructions' page. Let me know if you have any questions.

Best, 

Hani Z. Girgis, PhD
